/**
 * The onboarding States map's rules (P2B7Y): which jurisdiction a tap lands
 * on, how each view and inset is framed at a given width, where each
 * selection mark sits, and what every control is called. Numbers and
 * strings only, so all of it is testable under Node; the component draws it
 * with react-native-svg. A leaf apart from the geometry and the vocabulary.
 *
 * ## Why a map, and why the list stays
 *
 * Most shoppers recognise where they live faster than they can find it in a
 * 52-row list, so Map is the default. A map is also the worst possible
 * control for a screen-reader user and for the smallest jurisdictions, so the
 * searchable list is a first-class alternative over the SAME draft, never a
 * fallback that could drift from it.
 *
 * ## The geometry
 *
 * `state-map-geometry.ts` is generated by scripts/build-state-map.ts from the
 * Census Bureau's 2017 cartographic boundaries (via us-atlas 3.0.1, ISC),
 * vendored under assets/geography-sources/us-atlas/. The contiguous states
 * and the District of Columbia are drawn in d3.geoAlbersUsa's projection;
 * Alaska, Hawaii and Puerto Rico each sit in their own inset box. Nothing is
 * fetched: the map makes no network request of any kind.
 *
 * ## Small jurisdictions
 *
 * The Northeast view enlarges Maine to Maryland about four times, so Rhode
 * Island and Delaware become real targets. The District of Columbia is still
 * a few points across even there, so that view draws it as a round marker at
 * its own interior point, and a tap within `DC_TARGET_RADIUS` of the marker
 * chooses it. A tap that lands on water or on a border, outside every
 * shape, chooses the nearest shape within `NEAR_TOLERANCE` points, which is
 * what makes a coastline or an islet forgiving. The insets are whole-box
 * targets, however small their islands draw. And every jurisdiction is in
 * the list.
 */

import { stateNameForCode } from '@/domain/preferences';
import {
  STATE_MAP_INSET_VIEWS,
  STATE_MAP_SHAPES,
  STATE_MAP_VIEWS,
  type StateMapRegion,
  type StateMapShape,
  type StateMapViewBox,
} from '@/lib/state-map-geometry';

export type StatesSelectionMode = 'map' | 'list';
/** Map first: the list is one tap away, and holds the same draft. */
export const DEFAULT_SELECTION_MODE: StatesSelectionMode = 'map';

/** The two views of the contiguous map. */
export type StateMapView = keyof typeof STATE_MAP_VIEWS;
export type StateMapInset = Exclude<StateMapRegion, 'contiguous'>;

/** The inset boxes, left to right. */
export const INSET_ORDER: readonly StateMapInset[] = ['alaska', 'hawaii', 'puerto-rico'];
export const INSET_CODE: Record<StateMapInset, string> = {
  alaska: 'AK',
  hawaii: 'HI',
  'puerto-rico': 'PR',
};

/** The jurisdictions the Northeast view is framed around (Pennsylvania shows at its edge). */
export const NORTHEAST_CODES: readonly string[] = [
  'CT',
  'DC',
  'DE',
  'MA',
  'MD',
  'ME',
  'NH',
  'NJ',
  'NY',
  'RI',
  'VT',
];

/** Too small to draw as a target even enlarged: shown as a marker there. */
export const MARKER_CODES: readonly string[] = ['DC'];

/** How close to the marker, in points, a tap chooses the District. */
export const DC_TARGET_RADIUS = 12;
/** The marker's drawn diameter, in points. */
export const MARKER_SIZE = 20;
/** How far outside every shape, in points, a tap still finds the nearest one. */
export const NEAR_TOLERANCE = 10;
/** The check mark's size, in points (an icon-scale step). */
export const CHECK_SIZE = 16;
/** A shape shows its check only where it is at least this far from an edge, in points. */
export const CHECK_CLEARANCE = 5;
/** Each state's accessibility element: a square this size at its interior point. */
export const ELEMENT_SIZE = 32;

/**
 * The Northeast view is square; the contiguous view keeps the country's own
 * proportions. Width over height.
 */
export function viewAspect(view: StateMapView): number {
  if (view === 'northeast') return 1;
  const box = STATE_MAP_VIEWS.contiguous;
  return box.width / box.height;
}

export interface FittedView {
  box: StateMapViewBox;
  /** Points per projected unit. */
  scale: number;
  width: number;
  height: number;
}

/**
 * The view's frame at this width: its box grown symmetrically to the panel's
 * proportions, so the whole region shows, centred, and a point converts with
 * one scale and one offset (no letterboxing rule to mirror).
 */
export function fitView(view: StateMapView, width: number): FittedView {
  const base = STATE_MAP_VIEWS[view];
  const height = width / viewAspect(view);
  const scale = Math.min(width / base.width, height / base.height);
  const boxWidth = width / scale;
  const boxHeight = height / scale;
  return {
    box: {
      x: base.x - (boxWidth - base.width) / 2,
      y: base.y - (boxHeight - base.height) / 2,
      width: boxWidth,
      height: boxHeight,
    },
    scale,
    width,
    height,
  };
}

/** A point in the panel (points, from its top-left) as projected units. */
export function toMapPoint(fitted: FittedView, x: number, y: number): [number, number] {
  return [fitted.box.x + x / fitted.scale, fitted.box.y + y / fitted.scale];
}

/** A projected point as panel points. */
export function toPanelPoint(fitted: FittedView, point: readonly [number, number]) {
  return {
    x: (point[0] - fitted.box.x) * fitted.scale,
    y: (point[1] - fitted.box.y) * fitted.scale,
  };
}

// ── The shapes, parsed once for hit testing ─────────────────────────────────

/** Flat [x0, y0, x1, y1, …] rings. */
type Ring = number[];

/** Parses the generator's own grammar: `M x y l dx dy dx dy … z`, repeated. */
export function parseRings(d: string): Ring[] {
  const rings: Ring[] = [];
  const tokens = d.match(/[MlZz]|-?\d+(?:\.\d+)?/g) ?? [];
  let ring: Ring = [];
  let x = 0;
  let y = 0;
  let command = '';
  let pending: number[] = [];
  for (const token of tokens) {
    if (token === 'M' || token === 'l') {
      command = token;
      pending = [];
      continue;
    }
    if (token === 'z' || token === 'Z') {
      if (ring.length >= 6) rings.push(ring);
      ring = [];
      continue;
    }
    pending.push(Number(token));
    if (pending.length < 2) continue;
    const [a, b] = pending;
    pending = [];
    if (command === 'M') {
      x = a;
      y = b;
      ring = [x, y];
    } else {
      x += a;
      y += b;
      ring.push(x, y);
    }
  }
  return rings;
}

let parsed: Map<string, Ring[]> | null = null;
function ringsOf(code: string): Ring[] {
  if (parsed === null) {
    parsed = new Map(STATE_MAP_SHAPES.map((shape) => [shape.code, parseRings(shape.d)]));
  }
  return parsed.get(code) ?? [];
}

/** Even-odd across every ring, so holes and separate islands both hold. */
function contains(rings: Ring[], px: number, py: number): boolean {
  let hit = false;
  for (const ring of rings) {
    const n = ring.length;
    for (let i = 0, j = n - 2; i < n; j = i, i += 2) {
      const xi = ring[i];
      const yi = ring[i + 1];
      const xj = ring[j];
      const yj = ring[j + 1];
      if (yi > py !== yj > py && px < ((xj - xi) * (py - yi)) / (yj - yi) + xi) hit = !hit;
    }
  }
  return hit;
}

function distanceToEdges(rings: Ring[], px: number, py: number): number {
  let best = Infinity;
  for (const ring of rings) {
    const n = ring.length;
    for (let i = 0, j = n - 2; i < n; j = i, i += 2) {
      const ax = ring[j];
      const ay = ring[j + 1];
      const dx = ring[i] - ax;
      const dy = ring[i + 1] - ay;
      const length = dx * dx + dy * dy;
      const t =
        length === 0 ? 0 : Math.max(0, Math.min(1, ((px - ax) * dx + (py - ay) * dy) / length));
      best = Math.min(best, Math.hypot(px - (ax + t * dx), py - (ay + t * dy)));
    }
  }
  return best;
}

const CONTIGUOUS = STATE_MAP_SHAPES.filter((shape) => shape.region === 'contiguous');

export function shapeFor(code: string): StateMapShape | null {
  return STATE_MAP_SHAPES.find((shape) => shape.code === code) ?? null;
}

/**
 * The jurisdiction a tap at (x, y) in the contiguous panel chooses, or null
 * for open water or empty space. In the Northeast view the District's marker
 * wins within its radius; then the shape under the finger; then the nearest
 * shape within the tolerance.
 */
export function stateAtPoint(
  view: StateMapView,
  width: number,
  x: number,
  y: number,
): string | null {
  const fitted = fitView(view, width);
  const [px, py] = toMapPoint(fitted, x, y);
  if (view === 'northeast') {
    for (const code of MARKER_CODES) {
      const shape = shapeFor(code);
      if (shape === null) continue;
      const mark = toPanelPoint(fitted, shape.label);
      if (Math.hypot(mark.x - x, mark.y - y) <= DC_TARGET_RADIUS) return code;
    }
  }
  for (const shape of CONTIGUOUS) {
    const [x0, y0, x1, y1] = shape.bbox;
    if (px < x0 || px > x1 || py < y0 || py > y1) continue;
    if (contains(ringsOf(shape.code), px, py)) return shape.code;
  }
  const reach = NEAR_TOLERANCE / fitted.scale;
  let nearest: string | null = null;
  let nearestDistance = reach;
  for (const shape of CONTIGUOUS) {
    const [x0, y0, x1, y1] = shape.bbox;
    if (px < x0 - reach || px > x1 + reach || py < y0 - reach || py > y1 + reach) continue;
    const distance = distanceToEdges(ringsOf(shape.code), px, py);
    if (distance <= nearestDistance) {
      nearestDistance = distance;
      nearest = shape.code;
    }
  }
  return nearest;
}

// ── What sits on the panel ──────────────────────────────────────────────────

export interface StateMark {
  code: string;
  /** The interior point, in panel points. */
  x: number;
  y: number;
  /** Drawn as a round marker instead of a shape (the District, enlarged). */
  marker: boolean;
  /** Whether a check fits inside the shape at this scale. */
  checkFits: boolean;
  /** The check's size: the smaller icon step where the shape is narrow. */
  checkSize: 12 | 16;
}

/**
 * One mark per contiguous jurisdiction whose interior point is inside the
 * panel: the accessibility element, and the check when chosen. (Listed in
 * the canonical order; iOS itself orders the elements by position.)
 */
export function stateMarks(view: StateMapView, width: number): StateMark[] {
  const fitted = fitView(view, width);
  const marks: StateMark[] = [];
  for (const shape of CONTIGUOUS) {
    const { x, y } = toPanelPoint(fitted, shape.label);
    if (x < 0 || y < 0 || x > fitted.width || y > fitted.height) continue;
    const marker = view === 'northeast' && MARKER_CODES.includes(shape.code);
    marks.push({
      code: shape.code,
      x,
      y,
      marker,
      checkFits: marker || shape.clearance * fitted.scale >= CHECK_CLEARANCE,
      checkSize: !marker && shape.clearance * fitted.scale < CHECK_SIZE / 2 ? 12 : 16,
    });
  }
  return marks;
}

/** An element's square, kept inside the panel. */
export function elementFrame(mark: StateMark, fitted: { width: number; height: number }) {
  const half = ELEMENT_SIZE / 2;
  return {
    left: Math.max(0, Math.min(fitted.width - ELEMENT_SIZE, mark.x - half)),
    top: Math.max(0, Math.min(fitted.height - ELEMENT_SIZE, mark.y - half)),
    width: ELEMENT_SIZE,
    height: ELEMENT_SIZE,
  };
}

// ── The insets ──────────────────────────────────────────────────────────────

/** The inner padding of an inset box, in points. */
export const INSET_PADDING = 6;
/** No inset box is smaller than the touch target in either direction. */
export const INSET_MIN = 44;
/** Each inset's widest box, as a multiple of the row height. */
const INSET_MAX_WIDTH: Record<StateMapInset, number> = {
  alaska: 1.9,
  hawaii: 1.5,
  'puerto-rico': 1.4,
};

export interface InsetBox {
  inset: StateMapInset;
  code: string;
  width: number;
  height: number;
  /** The inset's own frame, grown to the box's inner proportions. */
  box: StateMapViewBox;
}

/**
 * The three inset boxes at this content width: one row height (a fifth of
 * the width, within 56–80pt), each box as wide as its drawing needs up to
 * its cap, each drawing contained with the box's padding. Each inset has its
 * own scale, as insets do; the box, not the islands, is the target.
 */
export function insetLayout(width: number): InsetBox[] {
  const height = Math.max(56, Math.min(80, Math.round(width * 0.19)));
  const inner = height - INSET_PADDING * 2;
  return INSET_ORDER.map((inset) => {
    const view = STATE_MAP_INSET_VIEWS[inset];
    const maxWidth = height * INSET_MAX_WIDTH[inset] - INSET_PADDING * 2;
    const scale = Math.min(inner / view.height, maxWidth / view.width);
    const boxWidth = Math.max(INSET_MIN, Math.round(view.width * scale + INSET_PADDING * 2));
    const innerWidth = (boxWidth - INSET_PADDING * 2) / scale;
    const innerHeight = inner / scale;
    return {
      inset,
      code: INSET_CODE[inset],
      width: boxWidth,
      height,
      box: {
        x: view.x - (innerWidth - view.width) / 2,
        y: view.y - (innerHeight - view.height) / 2,
        width: innerWidth,
        height: innerHeight,
      },
    };
  });
}

/** Every vocabulary code the map can choose, each exactly once. */
export function mapSelectableCodes(): string[] {
  return STATE_MAP_SHAPES.map((shape) => shape.code);
}

// ── Words ───────────────────────────────────────────────────────────────────

/** A jurisdiction's spoken name: always the full name, never the postal code. */
export function stateSpokenName(code: string): string {
  return stateNameForCode(code) ?? code;
}

export const MAP_MODE_LABEL = 'Map';
export const LIST_MODE_LABEL = 'List';
export const MAP_MODE_HINT = 'Shows the states on a map. Tap a state to choose it.';
export const LIST_MODE_HINT = 'Shows a searchable list of states.';
export const NORTHEAST_ZOOM_IN_LABEL = 'Zoom in on the Northeast';
export const NORTHEAST_ZOOM_IN_HINT =
  'Enlarges the map from Maine to Maryland so the small states are easier to tap.';
export const NORTHEAST_ZOOM_OUT_LABEL = 'Show the whole map';
export const NORTHEAST_ZOOM_OUT_HINT = 'Returns to the map of every state.';

/** The removal control beside a chosen jurisdiction names it. */
export function removeStateLabel(code: string): string {
  return `Remove ${stateSpokenName(code)}`;
}

// ── The glyphs this step adds to the icon set ───────────────────────────────

/**
 * The six interface glyphs the States step draws, from the same Lucide
 * family and commit as the allergen set (src/lib/allergen-icons.ts), the SVG
 * sources vendored in assets/icon-sources/lucide/ on 2026-09-24 and
 * rasterised by scripts/render-onboarding-assets.mjs.
 */
export const STATES_ICON_SOURCES = [
  { icon: 'map', lucideName: 'map' },
  { icon: 'list', lucideName: 'list' },
  { icon: 'x', lucideName: 'x' },
  { icon: 'check', lucideName: 'check' },
  { icon: 'zoom-in', lucideName: 'zoom-in' },
  { icon: 'zoom-out', lucideName: 'zoom-out' },
] as const;
export const STATES_ICONS_RETRIEVED_ON = '2026-09-24';

// ── Motion ──────────────────────────────────────────────────────────────────

/**
 * The helper mascot's one entrance: a fade and an 8pt settle, once, after
 * the screen's push has settled.
 */
export const MASCOT_ENTRANCE = { delay: 240, duration: 320, rise: 8 } as const;
/** Above this text scale the mascot yields its room to the Map/List control. */
export const HIDE_MASCOT_AT_SCALE = 1.5;
/** The helper mascot's square, in points. */
export const HELPER_MASCOT_SIZE = 72;
