/**
 * The onboarding States map (P2B7Y): the geometry covers the preference
 * vocabulary exactly, a tap lands on the jurisdiction under it in both
 * views and in the insets, Map and List edit one draft with the same rules,
 * and nothing about the map touches the network.
 */

import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { test } from 'node:test';

import { orderStateCodes, STATE_CODES_IN_ORDER, SUPPORTED_STATE_CODES } from '@/domain/preferences';
import {
  clearStateDraft,
  filterStateChoices,
  stateChoices,
  toggleStateCode,
} from '@/lib/personalization-screen';
import {
  DC_TARGET_RADIUS,
  DEFAULT_SELECTION_MODE,
  elementFrame,
  ELEMENT_SIZE,
  fitView,
  INSET_MIN,
  insetLayout,
  mapSelectableCodes,
  NORTHEAST_CODES,
  parseRings,
  removeStateLabel,
  shapeFor,
  stateAtPoint,
  stateMarks,
  stateSpokenName,
  toPanelPoint,
  type StateMapView,
} from '@/lib/state-map';
import { STATE_MAP_SHAPES, STATE_MAP_VIEWS } from '@/lib/state-map-geometry';

const ROOT = join(__dirname, '..', '..');
const read = (...parts: string[]) => readFileSync(join(ROOT, ...parts), 'utf8');

/** The reference phone's content width, and the smallest supported one's. */
const WIDTHS = [361, 343];

/** Where a jurisdiction's own interior point lands on the panel. */
function tapAt(view: StateMapView, width: number, code: string) {
  const shape = shapeFor(code);
  assert.ok(shape, `${code} has no shape`);
  return toPanelPoint(fitView(view, width), shape.label);
}

// ── 1–2. Coverage of the vocabulary ─────────────────────────────────────────

test('the canonical geometry covers every vocabulary entry exactly once', () => {
  const codes = mapSelectableCodes();
  assert.equal(codes.length, 52, '50 states, the District of Columbia and Puerto Rico');
  assert.equal(new Set(codes).size, codes.length, 'a jurisdiction is drawn twice');
  assert.deepEqual([...codes].sort(), [...SUPPORTED_STATE_CODES].sort());
  // In the canonical order, so the accessibility elements read alphabetically.
  assert.deepEqual(codes, STATE_CODES_IN_ORDER);
  for (const shape of STATE_MAP_SHAPES) {
    const rings = parseRings(shape.d);
    assert.ok(rings.length >= 1, `${shape.code} has no outline`);
    for (const ring of rings) assert.ok(ring.length >= 6, `${shape.code} has a degenerate ring`);
    const [x0, y0, x1, y1] = shape.bbox;
    assert.ok(x0 < x1 && y0 < y1, `${shape.code} has an empty box`);
    assert.ok(shape.clearance > 0, `${shape.code}'s mark point is not inside it`);
  }
  // Where each is drawn: three insets, everything else on the contiguous map.
  const region = Object.fromEntries(STATE_MAP_SHAPES.map((s) => [s.code, s.region]));
  assert.equal(region.AK, 'alaska');
  assert.equal(region.HI, 'hawaii');
  assert.equal(region.PR, 'puerto-rico');
  assert.equal(region.DC, 'contiguous');
  assert.equal(STATE_MAP_SHAPES.filter((s) => s.region === 'contiguous').length, 49);
});

test('no vocabulary entry is list-only today, and the list still holds every one', () => {
  const onMap = new Set(mapSelectableCodes());
  const listOnly = SUPPORTED_STATE_CODES.filter((code) => !onMap.has(code));
  // If a jurisdiction ever joins the vocabulary without geometry, this names
  // it; it stays choosable in List, which is built from the vocabulary alone.
  assert.deepEqual(listOnly, []);
  const list = filterStateChoices(stateChoices(), '').map((choice) => choice.code);
  assert.deepEqual(list, STATE_CODES_IN_ORDER);
});

test('the geometry is generated from the vendored Census-derived source, never hand-drawn', () => {
  const geometry = read('src', 'lib', 'state-map-geometry.ts');
  assert.ok(geometry.startsWith('/**\n * GENERATED by scripts/build-state-map.ts'));
  const generator = read('scripts', 'build-state-map.ts');
  assert.ok(generator.includes("'assets', 'geography-sources', 'us-atlas'"));
  // The vendored inputs are exactly the us-atlas 3.0.1 files, with their licence.
  const sha = (name: string) =>
    createHash('sha256')
      .update(readFileSync(join(ROOT, 'assets', 'geography-sources', 'us-atlas', name)))
      .digest('hex');
  assert.equal(
    sha('states-albers-10m.json'),
    '6e7bb086a3c791490361968a3094f377f7726c5d0c4900fec03cc42db2305a3d',
  );
  assert.equal(
    sha('states-10m.json'),
    'd76b391ccfa8bff601d51e3e3da5d43a89fa46cd5caca72ce731b383be5596d0',
  );
  assert.match(read('assets', 'geography-sources', 'us-atlas', 'LICENSE'), /Michael Bostock/);
  // geoAlbersUsa's 975×610 viewport holds the contiguous map.
  const box = STATE_MAP_VIEWS.contiguous;
  assert.ok(box.x >= 0 && box.y >= 0 && box.x + box.width <= 975 && box.y + box.height <= 615);
});

// ── 9. Local only ───────────────────────────────────────────────────────────

test('the map makes no network request: no URL, fetch, web view or map SDK', () => {
  for (const path of [
    ['src', 'lib', 'state-map.ts'],
    ['src', 'lib', 'state-map-geometry.ts'],
    ['src', 'components', 'onboarding', 'state-map.tsx'],
    ['src', 'components', 'onboarding', 'states-step.tsx'],
  ]) {
    const source = read(...path);
    for (const forbidden of [
      'fetch(',
      'http:',
      'https:',
      'XMLHttpRequest',
      'WebView',
      'uri:',
      'react-native-maps',
      '<MapView',
      'expo-location',
    ]) {
      assert.ok(!source.includes(forbidden), `${path.join('/')} contains ${forbidden}`);
    }
  }
  const pkg = JSON.parse(read('package.json')) as { dependencies: Record<string, string> };
  for (const name of Object.keys(pkg.dependencies)) {
    assert.ok(
      !/maps|mapbox|leaflet|webview|location|geo/i.test(name),
      `a mapping or location dependency: ${name}`,
    );
  }
  assert.ok('react-native-svg' in pkg.dependencies, 'the vector renderer is a declared dependency');
});

// ── 5–6. Taps land where they are aimed ─────────────────────────────────────

test('every contiguous jurisdiction is chosen by a tap at its own interior point', () => {
  for (const width of WIDTHS) {
    for (const shape of STATE_MAP_SHAPES.filter((s) => s.region === 'contiguous')) {
      const { x, y } = tapAt('contiguous', width, shape.code);
      assert.equal(stateAtPoint('contiguous', width, x, y), shape.code, `${shape.code} @${width}`);
    }
    // Enlarged, every Northeast jurisdiction is too, the District by its marker.
    for (const code of NORTHEAST_CODES) {
      const { x, y } = tapAt('northeast', width, code);
      assert.equal(stateAtPoint('northeast', width, x, y), code, `${code} enlarged @${width}`);
    }
  }
});

test('open water chooses nothing, a near miss chooses the nearest shape, the District has a real radius', () => {
  const width = 361;
  // The top-left corner of the contiguous panel is the Pacific.
  assert.equal(stateAtPoint('contiguous', width, 1, 1), null);
  // Far out in the Atlantic, east of the Northeast view's coast.
  assert.equal(stateAtPoint('northeast', width, width - 2, width - 2), null);
  // A few points off California's coast still chooses California.
  const fitted = fitView('contiguous', width);
  const ca = shapeFor('CA');
  assert.ok(ca);
  const coast = toPanelPoint(fitted, [ca.bbox[0], (ca.bbox[1] + ca.bbox[3]) / 2]);
  assert.equal(stateAtPoint('contiguous', width, coast.x - 4, coast.y), 'CA');
  // The District's marker takes taps within its radius, and no further.
  const dc = tapAt('northeast', width, 'DC');
  assert.equal(stateAtPoint('northeast', width, dc.x + DC_TARGET_RADIUS - 1, dc.y), 'DC');
  assert.notEqual(stateAtPoint('northeast', width, dc.x, dc.y - DC_TARGET_RADIUS - 8), 'DC');
});

test('California selects and deselects through the shared rule', () => {
  const { x, y } = tapAt('contiguous', 361, 'CA');
  const code = stateAtPoint('contiguous', 361, x, y);
  assert.equal(code, 'CA');
  const once = toggleStateCode([], code as string);
  assert.deepEqual(once, ['CA']);
  assert.deepEqual(toggleStateCode(once, 'CA'), []);
});

test('California, a Northeast state, Alaska and Hawaii select together, in canonical order', () => {
  const width = 361;
  const ca = tapAt('contiguous', width, 'CA');
  const ri = tapAt('northeast', width, 'RI');
  let draft: readonly string[] = [];
  draft = toggleStateCode(draft, stateAtPoint('contiguous', width, ca.x, ca.y) as string);
  draft = toggleStateCode(draft, stateAtPoint('northeast', width, ri.x, ri.y) as string);
  const insets = Object.fromEntries(insetLayout(width).map((box) => [box.inset, box.code]));
  draft = toggleStateCode(draft, insets.hawaii);
  draft = toggleStateCode(draft, insets.alaska);
  assert.deepEqual(draft, ['AK', 'CA', 'HI', 'RI']);
  assert.deepEqual(draft, orderStateCodes(draft));
});

// ── 3–4, 7. One draft, two modes ────────────────────────────────────────────

test('Map and List edit one draft with the same rules, so switching modes keeps every choice', () => {
  assert.equal(DEFAULT_SELECTION_MODE, 'map');
  // The same sequence, as a map tap or a list row, gives the same draft.
  const steps: ['map' | 'list', string][] = [
    ['map', 'CA'],
    ['list', 'NY'],
    ['map', 'RI'],
    ['list', 'PR'],
    ['map', 'NY'],
  ];
  let draft: readonly string[] = [];
  for (const [, code] of steps) draft = toggleStateCode(draft, code);
  assert.deepEqual(draft, ['CA', 'PR', 'RI']);
  // A List visit mounts over this draft and reports back through the same
  // commit, so its rows show exactly these, and a search hides without unchecking.
  const rows = filterStateChoices(stateChoices(), 'rhode').map((c) => c.code);
  assert.deepEqual(rows, ['RI']);
  assert.deepEqual(draft, ['CA', 'PR', 'RI']);
});

test('clearing an empty draft is a true no-op: the same reference comes back', () => {
  const empty: readonly string[] = [];
  assert.equal(clearStateDraft(empty), empty);
  assert.deepEqual(clearStateDraft(['CA', 'NY']), []);
});

// ── Layout and words ────────────────────────────────────────────────────────

test('the insets are whole touch targets and fit one row on the smallest phone', () => {
  for (const width of WIDTHS) {
    const boxes = insetLayout(width);
    assert.deepEqual(
      boxes.map((b) => b.code),
      ['AK', 'HI', 'PR'],
    );
    for (const box of boxes) {
      assert.ok(box.width >= INSET_MIN && box.height >= INSET_MIN, `${box.code} is under 44pt`);
    }
    const row = boxes.reduce((sum, b) => sum + b.width, 0) + 8 * (boxes.length - 1);
    assert.ok(row <= width, `the insets need ${row}pt of ${width}`);
  }
});

test('marks are one per visible jurisdiction, inside the panel, and the Northeast view enlarges', () => {
  const width = 361;
  const whole = stateMarks('contiguous', width);
  assert.equal(whole.length, 49);
  const enlarged = stateMarks('northeast', width);
  for (const code of NORTHEAST_CODES) {
    assert.ok(
      enlarged.some((m) => m.code === code),
      `${code} is missing from the enlarged view`,
    );
  }
  assert.ok(
    enlarged.find((m) => m.code === 'DC')?.marker,
    'the District is a marker when enlarged',
  );
  const small = fitView('contiguous', width).scale;
  const big = fitView('northeast', width).scale;
  assert.ok(big / small >= 3.5, `the Northeast is only ${big / small}× larger`);
  for (const mark of [...whole, ...enlarged]) {
    const frame = elementFrame(mark, fitView('contiguous', width));
    assert.equal(frame.width, ELEMENT_SIZE);
    assert.ok(frame.left >= 0 && frame.top >= 0);
  }
  // Large states carry a check; the smallest ones only when enlarged.
  assert.ok(whole.find((m) => m.code === 'CA')?.checkFits);
  assert.ok(!whole.find((m) => m.code === 'RI')?.checkFits);
  assert.ok(enlarged.find((m) => m.code === 'RI')?.checkFits);
});

test('every spoken name is the full name, never a postal code', () => {
  for (const code of SUPPORTED_STATE_CODES) {
    const name = stateSpokenName(code);
    assert.ok(name.length > 2 && name !== code, `${code} speaks as ${name}`);
    assert.equal(removeStateLabel(code), `Remove ${name}`);
  }
  assert.equal(stateSpokenName('DC'), 'District of Columbia');
  assert.equal(removeStateLabel('RI'), 'Remove Rhode Island');
});
