/**
 * P2B7U expand migration — BEHAVIOURAL proof, executed against a real
 * Postgres through real PostgREST on the local disposable stack.
 *
 * The sibling suite (preference-states-migration.test.ts) pins what the SQL
 * text may and may not contain. That cannot prove what the plpgsql does, and
 * the properties this migration has to get right are all runtime ones: that
 * two RPC signatures coexist and dispatch correctly, that both write the
 * canonical array AND the compatibility projection in one statement, that an
 * identical write still moves nothing, and that the projection is always the
 * array's first element. So these run for real.
 *
 * The stack is disposable and local: `supabase start` (Docker). When it is not
 * running — offline, CI without Docker, a machine that never started it — every
 * test here SKIPS with a message naming the command, so `npm run check` stays
 * green and fast without Docker and nobody mistakes an unrun proof for a
 * passing one.
 *
 * Credentials come from `supabase status -o env`, never from this repository:
 * the local keys are generated by the CLI, and a key-shaped string has no
 * business in version control even when it only unlocks a throwaway container.
 */

import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { test } from 'node:test';

interface LocalStack {
  restUrl: string;
  anonKey: string;
  serviceKey: string;
}

/** The local stack's own credentials, or null when it is not running. */
function localStack(): LocalStack | null {
  let env: string;
  try {
    env = execFileSync('supabase', ['status', '-o', 'env'], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
      timeout: 30_000,
    });
  } catch {
    return null;
  }
  const read = (key: string): string | null =>
    env.match(new RegExp(`^${key}="?([^"\n]+)"?$`, 'm'))?.[1] ?? null;
  const restUrl = read('REST_URL');
  const anonKey = read('ANON_KEY');
  const serviceKey = read('SERVICE_ROLE_KEY');
  if (!restUrl || !anonKey || !serviceKey) return null;
  return { restUrl, anonKey, serviceKey };
}

const STACK = localStack();
const SKIP = STACK
  ? false
  : 'the local Supabase stack is not running — start it with `supabase start` (needs Docker)';

/** Call an RPC exactly as a client does: PostgREST, publishable key, JSON body. */
async function rpc(
  stack: LocalStack,
  name: string,
  body: Record<string, unknown>,
): Promise<{ ok: boolean; status: number; message: string }> {
  const response = await fetch(`${stack.restUrl}/rpc/${name}`, {
    method: 'POST',
    headers: {
      apikey: stack.anonKey,
      Authorization: `Bearer ${stack.anonKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(body),
  });
  const text = await response.text();
  return { ok: response.ok, status: response.status, message: text };
}

interface StoredRow {
  installation_id: string;
  state_codes: string[];
  state_code: string | null;
  allergens: string[];
  retailer_ids: string[];
  updated_at: string;
}

/** Read a row back with the service role — what the delivery worker would see. */
async function readRow(stack: LocalStack, installationId: string): Promise<StoredRow | null> {
  const response = await fetch(
    `${stack.restUrl}/installation_preferences?installation_id=eq.${installationId}&select=*`,
    { headers: { apikey: stack.serviceKey, Authorization: `Bearer ${stack.serviceKey}` } },
  );
  // Read the body ONCE: a template literal in the assertion message would
  // consume it eagerly and leave nothing for the parse below.
  const body = await response.text();
  assert.ok(response.ok, `read failed: ${response.status} ${body}`);
  const rows = JSON.parse(body) as StoredRow[];
  return rows[0] ?? null;
}

/** Seed a row the way a PRE-P2B7U client would have: the singular RPC. */
async function writeLegacy(
  stack: LocalStack,
  installationId: string,
  stateCode: string | null,
  allergens: string[] = [],
  retailerIds: string[] = [],
): Promise<{ ok: boolean; status: number; message: string }> {
  return rpc(stack, 'set_installation_preferences', {
    p_installation_id: installationId,
    p_state_code: stateCode,
    p_allergens: allergens,
    p_retailer_ids: retailerIds,
  });
}

/** Write the way the NEW client does: the plural RPC. */
async function writePlural(
  stack: LocalStack,
  installationId: string,
  stateCodes: string[],
  allergens: string[] = [],
  retailerIds: string[] = [],
): Promise<{ ok: boolean; status: number; message: string }> {
  return rpc(stack, 'set_installation_preferences', {
    p_installation_id: installationId,
    p_state_codes: stateCodes,
    p_allergens: allergens,
    p_retailer_ids: retailerIds,
  });
}

let counter = 0;
/** A fresh installation id per case, so tests never share a row. */
function newInstallationId(): string {
  counter += 1;
  return `p2b7u-live-${String(counter).padStart(4, '0')}-aaaaaaaa`;
}

// ── Both signatures exist and dispatch by argument name ─────────────────────

test(
  'both RPC signatures are callable over PostgREST and resolve by argument name',
  {
    skip: SKIP,
  },
  async () => {
    const stack = STACK as LocalStack;
    // The legacy signature the DEPLOYED app calls. Keeping it working is the
    // entire point of an expand phase.
    const legacy = await writeLegacy(stack, newInstallationId(), 'CA');
    assert.ok(legacy.ok, `legacy RPC rejected: ${legacy.status} ${legacy.message}`);
    // The plural signature the new bundle calls.
    const plural = await writePlural(stack, newInstallationId(), ['CA', 'NY']);
    assert.ok(plural.ok, `plural RPC rejected: ${plural.status} ${plural.message}`);
  },
);

// ── Zero, one and many jurisdictions ────────────────────────────────────────

test('zero jurisdictions store an empty array and a null projection', { skip: SKIP }, async () => {
  const stack = STACK as LocalStack;
  const id = newInstallationId();
  assert.ok((await writePlural(stack, id, [])).ok);
  const row = await readRow(stack, id);
  assert.ok(row);
  assert.deepEqual(row.state_codes, []);
  assert.equal(row.state_code, null);
});

test('one jurisdiction stores a one-item array and projects it', { skip: SKIP }, async () => {
  const stack = STACK as LocalStack;
  const id = newInstallationId();
  assert.ok((await writePlural(stack, id, ['CA'])).ok);
  const row = await readRow(stack, id);
  assert.ok(row);
  assert.deepEqual(row.state_codes, ['CA']);
  assert.equal(row.state_code, 'CA');
});

test('many jurisdictions store the whole set, sorted distinct', { skip: SKIP }, async () => {
  const stack = STACK as LocalStack;
  const id = newInstallationId();
  assert.ok((await writePlural(stack, id, ['NY', 'MT', 'DC'])).ok);
  const row = await readRow(stack, id);
  assert.ok(row);
  // Sorted distinct is what makes an identical write comparable as a set,
  // whatever order the client sent.
  assert.deepEqual(row.state_codes, ['DC', 'MT', 'NY']);
  assert.equal(row.state_code, 'DC');
});

// ── The compatibility projection is never anything but states[0] ────────────

test(
  'state_code always equals state_codes[1], or null — through either RPC',
  {
    skip: SKIP,
  },
  async () => {
    const stack = STACK as LocalStack;
    const cases: { write: () => Promise<unknown>; id: string }[] = [];
    const plural: string[][] = [[], ['WY'], ['CA', 'NY'], ['PR', 'DC', 'AK'], ['TX', 'TX', 'TX']];
    for (const states of plural) {
      const id = newInstallationId();
      cases.push({ id, write: () => writePlural(stack, id, states) });
    }
    for (const single of ['CA', 'DC', 'PR', null]) {
      const id = newInstallationId();
      cases.push({ id, write: () => writeLegacy(stack, id, single) });
    }
    for (const entry of cases) {
      await entry.write();
      const row = await readRow(stack, entry.id);
      assert.ok(row, entry.id);
      const expected = row.state_codes.length === 0 ? null : row.state_codes[0];
      assert.equal(row.state_code, expected, `${entry.id}: projection drifted`);
    }
  },
);

// ── The legacy path maintains the canonical array (requirement 7) ───────────

test(
  'a legacy singular write maintains the canonical array atomically',
  {
    skip: SKIP,
  },
  async () => {
    const stack = STACK as LocalStack;
    const id = newInstallationId();
    // A pre-P2B7U client writing to an expanded database. The row it leaves must
    // be one the NEW delivery worker reads correctly, or a mixed-version
    // deployment silently loses the shopper's jurisdiction.
    assert.ok((await writeLegacy(stack, id, 'MT', ['peanut'], ['costco'])).ok);
    const stored = await readRow(stack, id);
    assert.ok(stored);
    assert.deepEqual(stored.state_codes, ['MT']);
    assert.equal(stored.state_code, 'MT');
    assert.deepEqual(stored.allergens, ['peanut']);
    assert.deepEqual(stored.retailer_ids, ['costco']);

    // Clearing through the legacy path clears both.
    assert.ok((await writeLegacy(stack, id, null, ['peanut'], ['costco'])).ok);
    const cleared = await readRow(stack, id);
    assert.ok(cleared);
    assert.deepEqual(cleared.state_codes, []);
    assert.equal(cleared.state_code, null);
  },
);

test(
  'a plural write over a legacy row replaces both representations',
  {
    skip: SKIP,
  },
  async () => {
    const stack = STACK as LocalStack;
    const id = newInstallationId();
    assert.ok((await writeLegacy(stack, id, 'CA')).ok);
    // The shopper updates the app and chooses three.
    assert.ok((await writePlural(stack, id, ['NY', 'CA', 'MT'])).ok);
    const row = await readRow(stack, id);
    assert.ok(row);
    assert.deepEqual(row.state_codes, ['CA', 'MT', 'NY']);
    assert.equal(row.state_code, 'CA');
  },
);

// ── Validation is preserved, on both paths ─────────────────────────────────

test(
  'duplicates are collapsed and invalid codes are rejected, not stored',
  {
    skip: SKIP,
  },
  async () => {
    const stack = STACK as LocalStack;
    const id = newInstallationId();
    assert.ok((await writePlural(stack, id, ['CA', 'CA', 'NY', 'CA'])).ok);
    assert.deepEqual((await readRow(stack, id))?.state_codes, ['CA', 'NY']);

    // An unsupported code is refused outright — the row is not half-written.
    const rejected = await writePlural(stack, id, ['CA', 'ZZ']);
    assert.ok(!rejected.ok, 'an invalid code was accepted');
    assert.match(rejected.message, /invalid state code/);
    assert.deepEqual(
      (await readRow(stack, id))?.state_codes,
      ['CA', 'NY'],
      'a refused write changed the row',
    );

    // The legacy path keeps its own validation too.
    const legacyRejected = await writeLegacy(stack, newInstallationId(), 'ZZ');
    assert.ok(!legacyRejected.ok);
    assert.match(legacyRejected.message, /invalid state code/);

    // The other closed vocabularies are untouched.
    const badAllergen = await writePlural(stack, newInstallationId(), ['CA'], ['gluten']);
    assert.ok(!badAllergen.ok);
    assert.match(badAllergen.message, /invalid allergen token/);
    const badId = await writePlural(stack, 'short', ['CA']);
    assert.ok(!badId.ok);
    assert.match(badId.message, /invalid installation id/);
  },
);

test('District of Columbia and Puerto Rico survive both paths', { skip: SKIP }, async () => {
  const stack = STACK as LocalStack;
  const plural = newInstallationId();
  assert.ok((await writePlural(stack, plural, ['DC', 'PR'])).ok);
  assert.deepEqual((await readRow(stack, plural))?.state_codes, ['DC', 'PR']);
  for (const code of ['DC', 'PR']) {
    const id = newInstallationId();
    assert.ok((await writeLegacy(stack, id, code)).ok, code);
    assert.deepEqual((await readRow(stack, id))?.state_codes, [code], code);
  }
});

test(
  'every one of the 52 supported jurisdictions is accepted at once',
  {
    skip: SKIP,
  },
  async () => {
    const stack = STACK as LocalStack;
    const { SUPPORTED_STATE_CODES } = await import('../../domain/preferences');
    assert.equal(SUPPORTED_STATE_CODES.length, 52);
    const id = newInstallationId();
    const result = await writePlural(stack, id, [...SUPPORTED_STATE_CODES]);
    assert.ok(result.ok, `the full set was rejected: ${result.message}`);
    const row = await readRow(stack, id);
    assert.equal(row?.state_codes.length, 52);
    assert.deepEqual(row?.state_codes, [...SUPPORTED_STATE_CODES].sort());
  },
);

// ── The delivery-safety horizon ─────────────────────────────────────────────

test('an identical write moves nothing, updated_at included', { skip: SKIP }, async () => {
  const stack = STACK as LocalStack;
  const id = newInstallationId();
  assert.ok((await writePlural(stack, id, ['CA', 'NY'], ['peanut'], ['costco'])).ok);
  const first = await readRow(stack, id);
  assert.ok(first);

  // The same selection, sent in a different order — the app re-syncs at launch.
  assert.ok((await writePlural(stack, id, ['NY', 'CA'], ['peanut'], ['costco'])).ok);
  const second = await readRow(stack, id);
  assert.equal(second?.updated_at, first.updated_at, 'a no-op moved the delivery horizon');

  // And through the legacy path, for a single-jurisdiction row.
  const legacyId = newInstallationId();
  assert.ok((await writeLegacy(stack, legacyId, 'TX')).ok);
  const before = await readRow(stack, legacyId);
  assert.ok((await writeLegacy(stack, legacyId, 'TX')).ok);
  assert.equal((await readRow(stack, legacyId))?.updated_at, before?.updated_at);

  // A REAL change does move it — otherwise the no-op above proves nothing.
  assert.ok((await writePlural(stack, id, ['CA', 'NY', 'MT'], ['peanut'], ['costco'])).ok);
  assert.notEqual((await readRow(stack, id))?.updated_at, first.updated_at);
});

// ── The migration creates nothing anywhere else ────────────────────────────

test('nothing the migration did put a row in any other table', { skip: SKIP }, async () => {
  const stack = STACK as LocalStack;
  for (const table of [
    'notification_events',
    'notification_deliveries',
    'push_subscriptions',
    'recall_cases',
    'ingest_runs',
  ]) {
    const response = await fetch(`${stack.restUrl}/${table}?select=*&limit=1`, {
      headers: { apikey: stack.serviceKey, Authorization: `Bearer ${stack.serviceKey}` },
    });
    assert.ok(response.ok, `${table}: ${response.status}`);
    assert.deepEqual(await response.json(), [], `${table} is not empty`);
  }
});

// ── The deployed code keeps working against the expanded database ──────────

test(
  'the CURRENTLY DEPLOYED delivery worker’s exact select still resolves',
  { skip: SKIP },
  async () => {
    const stack = STACK as LocalStack;
    // Byte-for-byte the column list on master today (src/server/push/push-store.ts
    // before P2B7U). If the expand phase had dropped state_code, this 400s and
    // every scheduled push run degrades to "no preferences" until the new
    // bundle ships.
    const legacySelect = 'installation_id,state_code,allergens,retailer_ids,updated_at';
    const response = await fetch(
      `${stack.restUrl}/installation_preferences?select=${legacySelect}`,
      { headers: { apikey: stack.serviceKey, Authorization: `Bearer ${stack.serviceKey}` } },
    );
    const body = await response.text();
    assert.ok(response.ok, `the deployed worker's select broke: ${response.status} ${body}`);
    const rows = JSON.parse(body) as { state_code: string | null }[];
    assert.ok(rows.length > 0, 'precondition: earlier cases wrote rows');

    // And the NEW worker's select, on the same database, in the same state.
    const pluralSelect = 'installation_id,state_codes,allergens,retailer_ids,updated_at';
    const next = await fetch(`${stack.restUrl}/installation_preferences?select=${pluralSelect}`, {
      headers: { apikey: stack.serviceKey, Authorization: `Bearer ${stack.serviceKey}` },
    });
    const nextBody = await next.text();
    assert.ok(next.ok, `the new worker's select broke: ${next.status} ${nextBody}`);
    assert.equal((JSON.parse(nextBody) as unknown[]).length, rows.length);
  },
);

test(
  'the shared implementation is not reachable with the publishable key',
  {
    skip: SKIP,
  },
  async () => {
    const stack = STACK as LocalStack;
    // Only the two wrappers are granted to anon; the impl must not become a
    // third, unvalidated entry point.
    const direct = await rpc(stack, 'apply_installation_preferences', {
      p_installation_id: newInstallationId(),
      p_state_codes: ['CA'],
      p_allergens: [],
      p_retailer_ids: [],
    });
    assert.ok(!direct.ok, 'anon could call the internal implementation');
    // Postgres refuses it, not PostgREST's router: SQLSTATE 42501,
    // insufficient_privilege, which PostgREST surfaces as a 401.
    assert.match(direct.message, /permission denied for function apply_installation_preferences/);
    assert.match(direct.message, /42501/);
  },
);
